name: TokensSystem
version: 1.0.0
description: A multiple token system
main: nu.granskogen.spela.TokenSystem.Main
author: Bingoo
depend: ['BossShopPro']
softdepend: [PlaceholderAPI]
api-version: 1.16

commands:
  tokens:

permissions:
  TokensSystem.see.self:
    description: Allows to see your token amount
    default: op
  TokensSystem.see.other:
    description: Allows to see other players token amount
    default: op
  TokensSystem.add:
    description: Allows to add tokens to users
    default: op
  TokensSystem.remove:
    description: Allows to remove tokens to users
    default: op
  TokensSystem.*:
    description: Wildcard permission
    default: op
    children:
      TokensSystem.add: true
      TokensSystem.remove: true
      TokensSystem.see.other: true
      TokensSystem.see.self: true