# Aktiverar JobsToken belöningar (ger token när någon går upp i level)
enableJobsToken: true
# Aktiverar VoteToken belöningar (ger token när någon röstar)
enableVoteToken: true

database:
  username: ""
  database: ""
  password: ""
  host: ""
  port: 3306
  prepStmtCacheSqlLimit: "2048"
  prepStmtCacheSize: "250"
  connectionTimeout: 500000 
  maximumPoolSize: 4
  useSSL: false