database:
  username: ""
  database: ""
  password: ""
  host: ""
  port: 3306
  prepStmtCacheSqlLimit: "2048"
  prepStmtCacheSize: "250"
  connectionTimeout: 500000 
  maximumPoolSize: 4
  useSSL: false